[package]
name = "app"
version = "0.7.2"
description = "Bounce"
authors = ["Aurabox"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

[build]
rustflags = ["--cfg", "tokio_allow_from_blocking_fd"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# App platform
tauri = { version = "2.4.0", features = ["tray-icon", "image-ico", "image-png", "unstable"] }

# Async runtime
tokio = { version = "1.43.0", features = ["full"] }

# DICOM library
dicom = { version = "0.8.0" }
dicom-ul = { version = "0.8.0", features = ["async"] }
dicom-transfer-syntax-registry = { version = "0.8.0" }
dicom-dictionary-std = { version = "0.8.0" }

# HTTP client
reqwest = { version = "0.12.9", features = ["json", "multipart", "stream"] }

# Serialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# Miscellaneous utilities
anyhow = "1.0.79"
zip = "2.2.1"
walkdir = "2.5.0"
snafu = "0.8"
tauri-plugin-store = "2"
tauri-plugin-process = "2"
tauri-plugin-shell = "2"
base64 = "0.22.1"
uuid = { version = "1.15.1", features = ['v4'] }
tokio-util = "0.7.13"
tauri-plugin-log = "2"
log = "0.4"
tauri-plugin-dialog = "2"
local-ip-address = "0.6.3"
tauri-plugin-opener = "2"
tauri-plugin-os = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
