[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# App platform
tauri = { version = "2", features = [] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# DICOM library
dicom = { version = "0.8.0" }
dicom-ul = { version = "0.8.0", features = ["async"] }
dicom-transfer-syntax-registry = { version = "0.8.0" }
dicom-dictionary-std = { version = "0.8.0" }

# HTTP client
reqwest = { version = "0.12.9", features = ["json", "multipart", "stream"] }
hyper = { version = "1.1.0", features = ["full"] }
http = "1.0.0"
log = "^0.4"

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# Serialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# Miscellaneous utilities
thiserror = "1.0.56"
anyhow = "1.0.79"
ring = "0.17.7"
clap = { version = "4.5.21", features = ["derive"] }
tar = "0.4.43"
flate2 = "1.0.35"
zip = "2.2.1"
sha2 = "0.10.8"
tokio-util = "0.7.12"
walkdir = "2.5.0"
snafu = "0.8"
bytes = "1.8.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
